//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WindowsFormsApp5.HuaTongWebReference1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://Aumex.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback xxcc_work_num_fOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPartnumOperationCompleted;
        
        private System.Threading.SendOrPostCallback funOperationCompleted;
        
        private System.Threading.SendOrPostCallback XXCC_LOT_PC_FOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBasicMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBarcodesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::WindowsFormsApp5.Properties.Settings.Default.WindowsFormsApp5_HuaTongWebReference2_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendProductCompletedEventHandler SendProductCompleted;
        
        /// <remarks/>
        public event ConnectionCompletedEventHandler ConnectionCompleted;
        
        /// <remarks/>
        public event xxcc_work_num_fCompletedEventHandler xxcc_work_num_fCompleted;
        
        /// <remarks/>
        public event GetPartnumCompletedEventHandler GetPartnumCompleted;
        
        /// <remarks/>
        public event funCompletedEventHandler funCompleted;
        
        /// <remarks/>
        public event XXCC_LOT_PC_FCompletedEventHandler XXCC_LOT_PC_FCompleted;
        
        /// <remarks/>
        public event SendBasicMessageCompletedEventHandler SendBasicMessageCompleted;
        
        /// <remarks/>
        public event SendBarcodesCompletedEventHandler SendBarcodesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Aumex.org/SendProduct", RequestNamespace="http://Aumex.org/", ResponseNamespace="http://Aumex.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendProduct(string products) {
            object[] results = this.Invoke("SendProduct", new object[] {
                        products});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendProductAsync(string products) {
            this.SendProductAsync(products, null);
        }
        
        /// <remarks/>
        public void SendProductAsync(string products, object userState) {
            if ((this.SendProductOperationCompleted == null)) {
                this.SendProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendProductOperationCompleted);
            }
            this.InvokeAsync("SendProduct", new object[] {
                        products}, this.SendProductOperationCompleted, userState);
        }
        
        private void OnSendProductOperationCompleted(object arg) {
            if ((this.SendProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendProductCompleted(this, new SendProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Aumex.org/Connection", RequestNamespace="http://Aumex.org/", ResponseNamespace="http://Aumex.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Connection() {
            object[] results = this.Invoke("Connection", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConnectionAsync() {
            this.ConnectionAsync(null);
        }
        
        /// <remarks/>
        public void ConnectionAsync(object userState) {
            if ((this.ConnectionOperationCompleted == null)) {
                this.ConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnectionOperationCompleted);
            }
            this.InvokeAsync("Connection", new object[0], this.ConnectionOperationCompleted, userState);
        }
        
        private void OnConnectionOperationCompleted(object arg) {
            if ((this.ConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConnectionCompleted(this, new ConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Aumex.org/xxcc_work_num_f", RequestNamespace="http://Aumex.org/", ResponseNamespace="http://Aumex.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string xxcc_work_num_f(string factory, string employeeId, string processId, string lineNum) {
            object[] results = this.Invoke("xxcc_work_num_f", new object[] {
                        factory,
                        employeeId,
                        processId,
                        lineNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void xxcc_work_num_fAsync(string factory, string employeeId, string processId, string lineNum) {
            this.xxcc_work_num_fAsync(factory, employeeId, processId, lineNum, null);
        }
        
        /// <remarks/>
        public void xxcc_work_num_fAsync(string factory, string employeeId, string processId, string lineNum, object userState) {
            if ((this.xxcc_work_num_fOperationCompleted == null)) {
                this.xxcc_work_num_fOperationCompleted = new System.Threading.SendOrPostCallback(this.Onxxcc_work_num_fOperationCompleted);
            }
            this.InvokeAsync("xxcc_work_num_f", new object[] {
                        factory,
                        employeeId,
                        processId,
                        lineNum}, this.xxcc_work_num_fOperationCompleted, userState);
        }
        
        private void Onxxcc_work_num_fOperationCompleted(object arg) {
            if ((this.xxcc_work_num_fCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.xxcc_work_num_fCompleted(this, new xxcc_work_num_fCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Aumex.org/GetPartnum", RequestNamespace="http://Aumex.org/", ResponseNamespace="http://Aumex.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPartnum(string productId) {
            object[] results = this.Invoke("GetPartnum", new object[] {
                        productId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPartnumAsync(string productId) {
            this.GetPartnumAsync(productId, null);
        }
        
        /// <remarks/>
        public void GetPartnumAsync(string productId, object userState) {
            if ((this.GetPartnumOperationCompleted == null)) {
                this.GetPartnumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPartnumOperationCompleted);
            }
            this.InvokeAsync("GetPartnum", new object[] {
                        productId}, this.GetPartnumOperationCompleted, userState);
        }
        
        private void OnGetPartnumOperationCompleted(object arg) {
            if ((this.GetPartnumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPartnumCompleted(this, new GetPartnumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Aumex.org/fun", RequestNamespace="http://Aumex.org/", ResponseNamespace="http://Aumex.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool fun() {
            object[] results = this.Invoke("fun", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void funAsync() {
            this.funAsync(null);
        }
        
        /// <remarks/>
        public void funAsync(object userState) {
            if ((this.funOperationCompleted == null)) {
                this.funOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfunOperationCompleted);
            }
            this.InvokeAsync("fun", new object[0], this.funOperationCompleted, userState);
        }
        
        private void OnfunOperationCompleted(object arg) {
            if ((this.funCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.funCompleted(this, new funCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Aumex.org/XXCC_LOT_PC_F", RequestNamespace="http://Aumex.org/", ResponseNamespace="http://Aumex.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string XXCC_LOT_PC_F(string factory, string productId, string processId) {
            object[] results = this.Invoke("XXCC_LOT_PC_F", new object[] {
                        factory,
                        productId,
                        processId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XXCC_LOT_PC_FAsync(string factory, string productId, string processId) {
            this.XXCC_LOT_PC_FAsync(factory, productId, processId, null);
        }
        
        /// <remarks/>
        public void XXCC_LOT_PC_FAsync(string factory, string productId, string processId, object userState) {
            if ((this.XXCC_LOT_PC_FOperationCompleted == null)) {
                this.XXCC_LOT_PC_FOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXXCC_LOT_PC_FOperationCompleted);
            }
            this.InvokeAsync("XXCC_LOT_PC_F", new object[] {
                        factory,
                        productId,
                        processId}, this.XXCC_LOT_PC_FOperationCompleted, userState);
        }
        
        private void OnXXCC_LOT_PC_FOperationCompleted(object arg) {
            if ((this.XXCC_LOT_PC_FCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XXCC_LOT_PC_FCompleted(this, new XXCC_LOT_PC_FCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Aumex.org/SendBasicMessage", RequestNamespace="http://Aumex.org/", ResponseNamespace="http://Aumex.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendBasicMessage(string proId, string lineId, string lineNum, string processId, string memberId, string productId, string productNum) {
            object[] results = this.Invoke("SendBasicMessage", new object[] {
                        proId,
                        lineId,
                        lineNum,
                        processId,
                        memberId,
                        productId,
                        productNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendBasicMessageAsync(string proId, string lineId, string lineNum, string processId, string memberId, string productId, string productNum) {
            this.SendBasicMessageAsync(proId, lineId, lineNum, processId, memberId, productId, productNum, null);
        }
        
        /// <remarks/>
        public void SendBasicMessageAsync(string proId, string lineId, string lineNum, string processId, string memberId, string productId, string productNum, object userState) {
            if ((this.SendBasicMessageOperationCompleted == null)) {
                this.SendBasicMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBasicMessageOperationCompleted);
            }
            this.InvokeAsync("SendBasicMessage", new object[] {
                        proId,
                        lineId,
                        lineNum,
                        processId,
                        memberId,
                        productId,
                        productNum}, this.SendBasicMessageOperationCompleted, userState);
        }
        
        private void OnSendBasicMessageOperationCompleted(object arg) {
            if ((this.SendBasicMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBasicMessageCompleted(this, new SendBasicMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Aumex.org/SendBarcodes", RequestNamespace="http://Aumex.org/", ResponseNamespace="http://Aumex.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendBarcodes(string barcode, string productId) {
            object[] results = this.Invoke("SendBarcodes", new object[] {
                        barcode,
                        productId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendBarcodesAsync(string barcode, string productId) {
            this.SendBarcodesAsync(barcode, productId, null);
        }
        
        /// <remarks/>
        public void SendBarcodesAsync(string barcode, string productId, object userState) {
            if ((this.SendBarcodesOperationCompleted == null)) {
                this.SendBarcodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBarcodesOperationCompleted);
            }
            this.InvokeAsync("SendBarcodes", new object[] {
                        barcode,
                        productId}, this.SendBarcodesOperationCompleted, userState);
        }
        
        private void OnSendBarcodesOperationCompleted(object arg) {
            if ((this.SendBarcodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBarcodesCompleted(this, new SendBarcodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendProductCompletedEventHandler(object sender, SendProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ConnectionCompletedEventHandler(object sender, ConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void xxcc_work_num_fCompletedEventHandler(object sender, xxcc_work_num_fCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class xxcc_work_num_fCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal xxcc_work_num_fCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetPartnumCompletedEventHandler(object sender, GetPartnumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPartnumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPartnumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void funCompletedEventHandler(object sender, funCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class funCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal funCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void XXCC_LOT_PC_FCompletedEventHandler(object sender, XXCC_LOT_PC_FCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XXCC_LOT_PC_FCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XXCC_LOT_PC_FCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendBasicMessageCompletedEventHandler(object sender, SendBasicMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBasicMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBasicMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendBarcodesCompletedEventHandler(object sender, SendBarcodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBarcodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBarcodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591